name: Johandielangman's Fortunes

on:
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set a build directory
        run: mkdir -p bin

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/fortune fortune.go

      - name: Build Windows binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o bin/fortune.exe fortune.go

      - name: Delete existing latest tag if exists
        run: |
          git tag -d latest || true
          git push origin :refs/tags/latest || true

      - name: Create latest tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag latest
          git push origin latest

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Release"
          draft: false
          prerelease: false
          files: |
            bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
